from tkinter import *
from tkinter import filedialog, messagebox
from tkinter import font as tkFont
import requests
import base64
import os
from PIL import Image, ImageTk

window = Tk()

try:
    ico = Image.open(os.environ["temp"] + "\\tungsten.png")
    photo = ImageTk.PhotoImage(ico)
    window.wm_iconphoto(False, photo)

except:
    # ouch
    icon = "iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAYAAAD0eNT6AAAe6ElEQVR4Xu3d227byLYFUAWIgfZDA9b/f6T10EAbiIFsq3eciy2bFFUkq9Yc+/XIFNeYS6zZipPz5eB/BAgQIECAQJzAl7iJDUyAAAECBAgcFABLQIAAAQIEAgUUgMDQjUyAAAECBBQAO0CAAAECBAIFFIDA0I1MgAABAgQUADtAgAABAgQCBRSAwNCNTIAAAQIEFAA7QIAAAQIEAgUUgMDQjUyAAAECBBQAO0CAAAECBAIFFIDA0I1MgAABAgQUADtAgAABAgQCBRSAwNCNTIAAAQIEFAA7QIAAAQIEAgUUgMDQjUyAAAECBBQAO0CAAAECBAIFFIDA0I1MgAABAgQUADtAgAABAgQCBRSAwNCNTIAAAQIEFAA7QIAAAQIEAgUUgMDQjUyAAAECBBQAO0CAAAECBAIFFIDA0I1MgAABAgQUADtAgAABAgQCBRSAwNCNTIAAAQIEFAA7QIAAAQIEAgUUgMDQjUyAAAECBBQAO0CAAAECBAIFFIDA0I1MgAABAgQUADtAgAABAgQCBRSAwNCNTIAAAQIEFAA7QIAAAQIEAgUUgMDQjUyAAAECBBQAO0CAAAECBAIFFIDA0I1MgAABAgQUADtAgAABAgQCBRSAwNCNTIAAAQIEFAA7QIAAAQIEAgUUgMDQjUyAAAECBBQAO0CAAAECBAIFFIDA0I1MgAABAgQUADtAgAABAgQCBRSAwNCNTIAAAQIEFAA7QIAAAQIEAgUUgMDQjUyAAAECBBQAO0CAAAECBAIFFIDA0I1MgAABAgQUADtAgAABAgQCBRSAwNCNTIAAAQIEFAA7QIAAAQIEAgUUgMDQjUyAAAECBBQAO0CAAAECBAIFFIDA0I1MgAABAgQUADtAgAABAgQCBRSAwNCNTIAAAQIEFAA7QIAAAQIEAgUUgMDQjUyAAAECBBQAO0CAAAECBAIFFIDA0I1MgAABAgQUADtAgAABAgQCBRSAwNCNTIAAAQIEFAA7QIAAAQIEAgUUgMDQjUyAAAECBBQAO0CAAAECBAIFFIDA0I1MgAABAgQUADtAgAABAgQCBRSAwNCNTIAAAQIEFAA7QIAAAQIEAgUUgMDQjUyAAAECBBQAO0CAAAECBAIFFIDA0I1MgAABAgQUADtAgAABAgQCBRSAwNCNTIAAAQIEFAA7QIAAAQIEAgUUgMDQjUyAAAECBBQAO0CAAAECBAIFFIDA0I1MgAABAgQUADtAgAABAgQCBRSAwNCNTIAAAQIEFAA7QIAAAQIEAgUUgMDQjUyAAAECBBQAO0CAAAECBAIFFIDA0I1MgAABAgQUADtAgAABAgQCBRSAwNCNTIAAAQIEFAA7QIAAAQIEAgUUgMDQjUyAAAECBBQAO0CAAAECBAIFFIDA0I1MgAABAgQUADtAgAABAgQCBRSAwNCNTIAAAQIEFAA7QIAAAQIEAgUUgMDQjUyAAAECBBQAO0CAAAECBAIFFIDA0I1MgAABAgQUADtAgAABAgQCBRSAwNCNTIAAAQIEFAA7QIAAAQIEAgUUgMDQjUyAAAECBBQAO0CAAAECBAIFFIDA0I1MgAABAgQUADtAgAABAgQCBRSAwNCNTIAAAQIEFAA7QIAAAQIEAgUUgMDQjUyAAAECBBQAO0CAAAECBAIFFIDA0I1MgAABAgQUADtAgAABAgQCBRSAwNCNTIAAAQIEFAA7QIAAAQIEAgUUgMDQjUyAAAECBBQAO0CAAAECBAIFFIDA0I1MgAABAgQUADtAgAABAgQCBRSAwNCNTIAAAQIEFAA7QIAAAQIEAgUUgMDQjUyAAAECBBQAO0CAAAECBAIFFIDA0I1MgAABAgQUADtAgAABAgQCBRSAwNCNTIAAAQIEFAA7QIAAAQIEAgUUgMDQjUyAAAECBBQAO0CAAAECBAIFFIDA0I1MgAABAgQUADtAgAABAgQCBRSAwNCNTIAAAQIEFAA7QIAAAQIEAgUUgMDQjUyAAAECBBQAO0CAAAECBAIFFIDA0I1MgAABAgQUADtAgAABAgQCBRSAwNCNTIAAAQIEFAA7QIAAAQIEAgUUgMDQjUyAAAECBBQAO0CAAAECBAIFFIDA0I1MgAABAgQUADtAgAABAgQCBRSAwNCNTIAAAQIEFAA7QIAAAQIEAgUUgMDQjUyAAAECBBQAO0CAAAECBAIFFIDA0I1MgAABAgQUADtAgAABAgQCBRSAwNCNTIAAAQIEFAA7QIAAAQIEAgUUgMDQjUyAAAECBBQAO0CAAAECBAIFFIDA0I1MgAABAgQUADtAgAABAgQCBRSAwNCNTIAAAQIEFAA7QIAAAQIEAgUUgMDQjUyAAAECBBQAO0CAAAECBAIFFIDA0I1MgAABAgQUADtAgAABAgQCBRSAwNCNTIAAAQIEFAA7QIAAAQIEAgUUgMDQjUyAAAECBBQAO0CAAAECBAIFFIDA0I1MgAABAgQUADtAgAABAgQCBRSAwNCNTIAAAQIEFAA7QIAAAQIEAgUUgMDQjUyAAAECBBQAO0CAAAECBAIFFIDA0I1MgAABAgQUADtAgAABAgQCBRSAwNCNTIAAAQIEFIDAHfj+8r8vL/8LHN3ILwLytwYECJwFHAKBe3A+AM5jPz09He7v7+1A2A7IPyxw4xL4QMDDP3A1Xg+A19EVgawlkH9W3qYl8JGAAhC4G28PgFcCfyyQsQzyz8jZlASmBBSAKaGC//ePDgBFoGDYF0aSf0bOpiQwJaAATAkV/L9PHQCKQMHQfxtJ/rXzNR2BuQIKwFypQq+bewAoAoVCX1AA5F8zf1MR+PnZRpEncG0BOAv5RcE6eyL/OlmahMAtAr4BuEVv0J9dcgC8jno6nQ7H49HeDJr9+bblP3B4bp1AQwEP8oaYo1zqlgPA18KjpPzxfcp//AxNQKCFgALQQnGwa7Q4ABSBwUL/7XblP2527pxASwEFoKXmINdqeQAoAoOEvlIBkP94+btjAj8/tyjyBNYoAA6CcfZI/uNk5U4JrCngG4A1dTu99poHwHlkf2Og0+B/3Jb8+87H3RHYSkAB2Eq6o/dZ+wDwbUBHYV+4Ffn3nY+7I7CVgAKwlXRH77PVAaAIdBT6b7ci/z5zcVcEthZQALYW7+D9tj4AFIEOQt+xAMi/r/zdDYGfn0kUeQJ7FQAHQR+7Jv8+cnAXBPYW8A3A3gns8P57HwDnkZ+fnw93d3f2T/47CHhLAgTOAh7AgXvQQwF4Zfc3BrZfQPlvb+4dCfQooAD0mMrK99TTAeCPBVYO+8Ll5b+9uXck0KOAAtBjKivfU48HgCKwcui/XV7+21l7JwI9CygAPaez0r31fAAoAiuFPkgBkP/6+XsHAj8/ZyjyBEYoAA6C9fZS/uvZujKBkQR8AzBSWo3udaQD4DyyXxRsFPyPy8i/raerERhVQAEYNbkb7nu0A+B1VEXghtAH+yOAS5PKv03+rkLAHwEE78CoBcAfC7RZWvm3cXQVAqML+AZg9AQX3P/oB4AisCD0At8AvJ36y8v/bpPw0wSyBXyAAvOvUgAUgWXLK/9lbn6KQDUBBaBaojPmqXYAKAIzQi/4DYBvBK7L3asJvPvMIMkTqFoAzkn6RbHpfZb/tJFXEEgQ8A1AQsofzFj5IPjnn38Of//9t/3+ZL/lH/zhNzqBFwEPSGtwqHwQ+EWx6QWX/7SRVxCoKKAAVEx14UwOgoVwRX5M/kWCNAaBmQIKwEyolJf9+++/3//666+y4/pG4PNo5V929Q1G4J2AAmApLgo4CLIXQ/7Z+Zs+Q0AByMh58ZSVvxb2Nwam10L+00ZeQWBUAQVg1OQ2vu/KB8HpdDocj0efhU92Sv4bf+C8HYENBDz0NkCu9BaVDwK/HzC9qfKfNvIKAqMIKACjJNXZfToIOgtk49uR/8bg3o7ACgIKwAqoSZd0ECSl/X5W+Wfnb/qxBRSAsfPr4u4fHx+/Pzw8dHEva9yEPxr4XFX+a2ydaxJYX0ABWN845h0q/9Uxf2Ngeo3lP23kFQR6ElAAekqjyL18+/bt+9evX4tM8+cYvg2YjlX+00ZeQaAHAQWghxSK3oM/Hy4a7Myx5D8TyssI7CSgAOwEn/S2DoKktN/PKv/s/E3fr4AC0G825e7MQVAu0qsGkv9VXF5MYHUBBWB1Ym/wVqDqQeAXBeftuvznOXkVgbUFFIC1hV3/QwEHQfZyyD87f9PvL6AA7J9B9B1U/qtj/sbA9GrLf9rIKwisJaAArCXrulcJOAiu4ir3YvmXi9RAAwgoAAOElHSLVb8WPmfoG4HpTZb/tJFXEGgloAC0knSdpgIOgqacw11M/sNF5oYHFFAABgwt6ZarHgT+xsC8LZb/PCevIrBEQAFYouZnNhdwEGxO3tUbyr+rONxMEQEFoEiQKWNUPQj8fsC8DZb/PCevIjBHQAGYo+Q1XQn4jfGu4tj8ZuS/Obk3LCqgABQNNmEsB0FCyh/PKP/s/E1/u4ACcLuhK+wsUPVr4TOrPxqYXi75Txt5BYFLAgqAvSgjUPUg8DcG5q2o/Oc5eRWBVwEFwC6UE6h6EJxOp8PxePSZndhY+Zf7SBtoJQEPk5VgXXZ/gaoHgT8WmLdb8p/n5FW5AgpAbvYxkzsIYqK+OKj8s/M3/ccCCoDtiBDwG+MRMX84pPyz8zf9ZQEFwGZECTgIouJ+N6z8s/M3/Z8CCoCNiBSo+rWwvzEwb53lP8/Jq2oLKAC18zXdhEDVg8AvCs5bffnPc/KqmgIKQM1cTXWlgIPgSrBiL5d/sUCNM0tAAZjF5EUpAg6ClKQvzyn/7PzTplcA0hI37ywBB8EsprIvkn/ZaA32m4ACYB0IfCDw+Pj4/eHhoZzP8/Pz4e7uzmd/Iln5l1t9A70R8BCwEgQmBKr+1TF/Y2De6st/npNXjSegAIyXmTveSaDqQeBvDMxbKPnPc/KqcQQUgHGycqedCPjz4U6C2Ok25L8TvLdtLqAANCd1wRQBB0FK0pfnlH92/hWmVwAqpGiGXQUcBLvy7/7m8t89AjewUEABWAjnxwi8Fah4EPhFwfl7Lv/5Vl7Zh4AC0EcO7qKQgIOgUJgLRpH/AjQ/souAArALuzetLuA3xqsn/Pl88s/Of5TpFYBRknKfQwo4CIaMrdlNy78ZpQutIKAArIDqkgQSfj/gPKN/Q2Derlf8YwH5z8u+51cpAD2n497KCVQ7CBSA61ZU/td5efW6AgrAur6uTuCiQJWDQAFYtuDyX+bmp9oKKABtPV2NwFUCox8ECsBVcb97sfxv8/PTtwkoALf5+WkCTQRGPQgUgCbxH+TfxtFVrhNQAK7z8moCqwmM+BvjCkC7dZB/O0tXmiegAMxz8ioCmwmMdBAoAO3XQv7tTV3xsoACYDMIdCowwtfCCsB6yyP/9Wxd+f8CCoBNINC5QM8HgQKw/vLIf33j1HdQAFKTN/dQAr0eAgrANmsk/22c095FAUhL3LzDCfT68P/vK8SX/w0HOtgNy3+wwAa6XR/egcJyqzkCj4+P3x8eHrofWAFYJyL5r+Pqqn8KKAA2gkBHAqM8+F/JFIC2yyP/tp6u9rmAAmBDCHQgMNJf/fqdSwFoszzyb+PoKtcJKADXeXk1gaYC3759+/7169em19zyYgrAbdryv83PT98moADc5uenCSwSGP3B748AFsX+84fkf5ufn24joAC0cXQVArMEev6N7lkDvHmRbwCuU5P/dV5eva6AArCur6sT+E+g2oPfNwDXLbb8r/Py6m0EFIBtnL1LqEDVB78CMG+h5T/Pyav2EVAA9nH3rsUFqj/4FYDPF1j+xT/gRcZTAIoEaYw+BFIe/KfT6XA8Hj0/3qyd/Pv4HLqLeQI+wPOcvIrAhwKj/eMtt0Tp4H+vJ/9bNsrP7imgAOyp772HFvDgHzq+m29e/jcTusDOAgrAzgF4+/EERv1X25ZI+y/+92ryX7JJfqZHAQWgx1TcU5cCVf7xljm4Dv73SvKfszleM5KAAjBSWu51FwEP/l3Yu3lT+XcThRtpLKAANAZ1uToCKb/RfU7Mv+j3fm/lX+ezbJLLAgqAzSDwRsCDP3sl5J+df9L0CkBS2mb9VMCDP3tB5J+df+L0CkBi6mb+Q8CDP3sh5J+df/L0CkBy+uGze/BnL4D8s/M3/cvv/kAgkCSQ9I+3+OW+95st/6RPu1mnBBSAKSH/9xICHvwlYlw8hPwX0/nBwgIKQOFwjXY4JP2rbf6L//3Gy99TgMDHAgqA7SgpkPSPtzj436+w/Et+rA3VWEABaAzqcvsKePDv67/3u8t/7wS8/0gCCsBIabnXDwWSfqPbf/G/XwP5ezgQuF5AAbjezE90JODB31EYO9yK/HdA95ZlBBSAMlFmDeLBn5X322nln52/6dsIKABtHF1lIwEP/o2gO30b+XcajNsaUkABGDK2vJv24M/L/PeJ5Z+dv+nXEVAA1nF11QYCaf94y5nM/1veX4sj/wYfIpcg8ImAAmA9uhPw4O8ukk1vSP6bcnuzYAEFIDj83kZP+zvc/ov/zw2Uf2+fSPdTXUABqJ7wAPN58A8Q0oq3KP8VcV2agD8CsAM9CqT9Ypf/4v9zC+Xf46fSPSUJ+AYgKe1OZk178D8/Px/u7u581n7sn/w7+SC6jXgBD6X4FdgOwIN/O+se30n+PabinpIFFIDk9Dea3YN/I+hO30b+nQbjtuIFFID4FVgPwIN/PdsRriz/EVJyj8kCCkBy+ivN7sG/Euwgl5X/IEG5zXgBBSB+BdoAJP7jLX6579fuyL/N58hVCGwpoABsqV3wvRIf/E9PT4f7+3ufnZd9ln/BD7WRYgQ8xGKibjto4j/e4uD/tUPyb/t5cjUCewgoAHuoD/yeiQ/+0+l0OB6PPisveyv/gT+8bp3AGwEPNSsxSyDtF7vOKA7+X6sh/1kfEy8iMJSAAjBUXNvfrAf/9uY9vaP8e0rDvRBoK6AAtPUsczUP/jJRLhpE/ovY/BCBoQQUgKHiWv9mPfjXN+75HeTfczrujUBbAQWgreewV/PgHza6Jjcu/yaMLkJgKAEFYKi42t+sB39705GuKP+R0nKvBNoKKABtPYe4WuI/3nIO5svL/4YIaOWblP/KwC5PYBABD8RBgmp5m2n/1efg/3N75N/y0+RaBMYVUADGzW7xnaccAA7+yysi/8UfHT9IoJSAAlAqznnDVD8AHPyf74H8531OvIpAdQEFoHrCF+aregA4+Octs/znOXkVgeoCCkD1hAMKgIP/uiWuVgDkf13+Xk3gVUABCNyFKgeAB/+y5ZX/Mjc/RaCagAJQLdEZ84x+ADj4Z4T8yUvkf5ufnyZQRUABqJLkFXOMegA4+K8IuWABkH+b/F2FgD8CCN6B0QqAB3/bZZV/W09XIzCqgG8ARk3uhvse5QBw8N8QcoFvAOS/Tv6uSsA3AME70HsB8OBfdznlv66vqxMYRcA3AKMk1fA+ez0AHPwNQx7wGwD5b5O/dyHgG4DgHeitAHjwb7uM8t/W27sR6FXANwC9JrPiffVyADj4Vwx5gG8A5L9P/t6VgG8Agndg7wLgwb/v8sl/X3/vTqAXAd8A9JLEhvex1wHg4N8w5A6/AZB/H/m7CwK+AQjega0LgAd/X8sm/77ycDcE9hLwDcBe8ju+71YHgIN/x5A7+AZA/n3m764I+AYgeAfWLADPz8+Hu7s7xbLj/ZJ/x+G4NQIbCnhQb4jdy1utcQA4+HtJd/o+5D9t5BUEEgQUgISU38zY8gBw8I+3QPIfLzN3TGANAQVgDdXOr9niAHDwdx7yyr8DIP9x83fnBPwOQPAO3FIAPPjHXxz5j5+hCQi0EPANQAvFwa6x5ABw8A8WcuNvAORfJ3+TEPANQPAOXFMAPPjrLYr862VqIgJLBHwDsERt8J+ZcwA8PT0d7u/v7cfgWV+6ffkXDNVIBBYIeMAvQBv9Rz47ABz8o6c7ff/ynzbyCgIJAgpAQspvZrx0AJxOp8PxeLQPAfsg/4CQjUhghoAH/gykai/5/QBw8FdLd3oe+U8beQWBBAEFICHlC98AOPgDg/8x8rkAyD83f5MTeBVQAOwCAQIECBAIFFAAAkM3MgECBAgQUADsAAECBAgQCBRQAAJDNzIBAgQIEFAA7AABAgQIEAgUUAACQzcyAQIECBBQAOwAAQIECBAIFFAAAkM3MgECBAgQUADsAAECBAgQCBRQAAJDNzIBAgQIEFAA7AABAgQIEAgUUAACQzcyAQIECBBQAOwAAQIECBAIFFAAAkM3MgECBAgQUADsAAECBAgQCBRQAAJDNzIBAgQIEFAA7AABAgQIEAgUUAACQzcyAQIECBBQAOwAAQIECBAIFFAAAkM3MgECBAgQUADsAAECBAgQCBRQAAJDNzIBAgQIEFAA7AABAgQIEAgUUAACQzcyAQIECBBQAOwAAQIECBAIFFAAAkM3MgECBAgQUADsAAECBAgQCBRQAAJDNzIBAgQIEFAA7AABAgQIEAgUUAACQzcyAQIECBBQAOwAAQIECBAIFFAAAkM3MgECBAgQUADsAAECBAgQCBRQAAJDNzIBAgQIEFAA7AABAgQIEAgUUAACQzcyAQIECBBQAOwAAQIECBAIFFAAAkM3MgECBAgQUADsAAECBAgQCBRQAAJDNzIBAgQIEFAA7AABAgQIEAgUUAACQzcyAQIECBBQAOwAAQIECBAIFFAAAkM3MgECBAgQUADsAAECBAgQCBRQAAJDNzIBAgQIEFAA7AABAgQIEAgUUAACQzcyAQIECBBQAOwAAQIECBAIFFAAAkM3MgECBAgQUADsAAECBAgQCBRQAAJDNzIBAgQIEFAA7AABAgQIEAgUUAACQzcyAQIECBBQAOwAAQIECBAIFFAAAkM3MgECBAgQUADsAAECBAgQCBRQAAJDNzIBAgQIEFAA7AABAgQIEAgUUAACQzcyAQIECBBQAOwAAQIECBAIFFAAAkM3MgECBAgQUADsAAECBAgQCBRQAAJDNzIBAgQIEFAA7AABAgQIEAgUUAACQzcyAQIECBBQAOwAAQIECBAIFFAAAkM3MgECBAgQUADsAAECBAgQCBRQAAJDNzIBAgQIEFAA7AABAgQIEAgUUAACQzcyAQIECBBQAOwAAQIECBAIFFAAAkM3MgECBAgQUADsAAECBAgQCBRQAAJDNzIBAgQIEFAA7AABAgQIEAgUUAACQzcyAQIECBBQAOwAAQIECBAIFFAAAkM3MgECBAgQUADsAAECBAgQCBRQAAJDNzIBAgQIEFAA7AABAgQIEAgUUAACQzcyAQIECBBQAOwAAQIECBAIFFAAAkM3MgECBAgQUADsAAECBAgQCBRQAAJDNzIBAgQIEFAA7AABAgQIEAgUUAACQzcyAQIECBBQAOwAAQIECBAIFFAAAkM3MgECBAgQUADsAAECBAgQCBRQAAJDNzIBAgQIEFAA7AABAgQIEAgUUAACQzcyAQIECBBQAOwAAQIECBAIFFAAAkM3MgECBAgQUADsAAECBAgQCBRQAAJDNzIBAgQIEFAA7AABAgQIEAgUUAACQzcyAQIECBBQAOwAAQIECBAIFFAAAkM3MgECBAgQUADsAAECBAgQCBRQAAJDNzIBAgQIEFAA7AABAgQIEAgUUAACQzcyAQIECBBQAOwAAQIECBAIFFAAAkM3MgECBAgQUADsAAECBAgQCBRQAAJDNzIBAgQIEFAA7AABAgQIEAgUUAACQzcyAQIECBBQAOwAAQIECBAIFFAAAkM3MgECBAgQUADsAAECBAgQCBRQAAJDNzIBAgQIEFAA7AABAgQIEAgUUAACQzcyAQIECBBQAOwAAQIECBAIFFAAAkM3MgECBAgQUADsAAECBAgQCBRQAAJDNzIBAgQIEFAA7AABAgQIEAgUUAACQzcyAQIECBBQAOwAAQIECBAIFFAAAkM3MgECBAgQUADsAAECBAgQCBRQAAJDNzIBAgQIEFAA7AABAgQIEAgUUAACQzcyAQIECBBQAOwAAQIECBAIFFAAAkM3MgECBAgQUADsAAECBAgQCBRQAAJDNzIBAgQIEFAA7AABAgQIEAgUUAACQzcyAQIECBBQAOwAAQIECBAIFFAAAkM3MgECBAgQUADsAAECBAgQCBRQAAJDNzIBAgQIEFAA7AABAgQIEAgUUAACQzcyAQIECBBQAOwAAQIECBAIFFAAAkM3MgECBAgQUADsAAECBAgQCBRQAAJDNzIBAgQIEFAA7AABAgQIEAgUUAACQzcyAQIECBBQAOwAAQIECBAIFFAAAkM3MgECBAgQUADsAAECBAgQCBRQAAJDNzIBAgQIEFAA7AABAgQIEAgUUAACQzcyAQIECBBQAOwAAQIECBAIFFAAAkM3MgECBAgQUADsAAECBAgQCBRQAAJDNzIBAgQIEFAA7AABAgQIEAgUUAACQzcyAQIECBBQAOwAAQIECBAIFFAAAkM3MgECBAgQUADsAAECBAgQCBRQAAJDNzIBAgQIEFAA7AABAgQIEAgUUAACQzcyAQIECBBQAOwAAQIECBAIFFAAAkM3MgECBAgQ+B+Epr5bkXi8oQAAAABJRU5ErkJggg=="

    img = icon.encode()
    img_data = base64.b64decode(img)

    with open(os.environ["temp"] + "\\tungsten.png", "wb") as iconfile:
        iconfile.write(img_data)

    ico = Image.open(os.environ["temp"] + "\\tungsten.png")
    photo = ImageTk.PhotoImage(ico)
    window.wm_iconphoto(False, photo)

def video():
    # Download the file!

    headers = {'Content-type': 'application/json', 'Accept': 'application/json'}

    req = requests.post("https://co.wuk.sh/api/json", json={"url": url.get()}, headers=headers)

    json = req.json()

    fileUrl = json["url"]

    selected_folder = filedialog.askdirectory()

    filename = fileUrl.split("&i=")[-1]

    messagebox.Message(message="Downloading to " + selected_folder + "\\" + filename + ".mp4").show()

    contents = requests.get(fileUrl).content

    with open(selected_folder + "\\" + filename + ".mp4", "wb") as file:
        file.write(contents)

    messagebox.Message(message="Done!").show()

def audio():
    # Download the file!

    headers = {'Content-type': 'application/json', 'Accept': 'application/json'}

    req = requests.post("https://co.wuk.sh/api/json", json={"url": url.get(), "isAudioOnly": True}, headers=headers)

    json = req.json()

    try:
        json["url"]

    except:
        try:
            messagebox.Message(message=json["text"]).show()

        except:
            messagebox.Message(message="WHAT DID YOU DO").show()

    fileUrl = json["url"]

    selected_folder = filedialog.askdirectory()

    filename = fileUrl.split("&i=")[-1]

    messagebox.Message(message="Downloading to " + selected_folder + "\\" + filename + ".mp3").show()

    contents = requests.get(fileUrl).content

    with open(selected_folder + "\\" + filename + ".mp3", "wb") as file:
        file.write(contents)

    messagebox.Message(message="Done!").show()

btnFont = tkFont.Font(family="Jetbrains Mono", size=24)

url = StringVar(window)

window.geometry("600x160")
window.configure(background="black")
window.title("Tungsten")

label = Label(window, text="Tungsten", font=("Jetbrains Mono", 32), foreground="white", background="black")
label.pack()

urlEntry = Entry(window, textvariable=url, font=("Jetbrains Mono", 24), width=30, bg="black", fg="white")

urlEntry.config(highlightthickness=2)
urlEntry.config(highlightbackground = "white", highlightcolor= "white")

audioButton = Button(window, text="MP3", width=15, command=audio, font=btnFont, bg="black", fg="white")
videoButton = Button(window, text="MP4", width=15, command=video, font=btnFont, bg="black", fg="white")

audioButton.config(highlightthickness=2)
audioButton.config(highlightbackground = "white", highlightcolor= "white")

videoButton.config(highlightthickness=2)
videoButton.config(highlightbackground = "white", highlightcolor= "white")

urlEntry.pack()
audioButton.pack(anchor="n", side=LEFT)
videoButton.pack(anchor="n", side=RIGHT)

window.resizable(False,False)

window.mainloop()
